import { AppleNavbar } from "./todo/ConfirmModal";
import { AuthProvider } from "./auth-context";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-gray-100 to-gray-300 min-h-screen`}
      >
        <AuthProvider>
          <AppleNavbar />
          <div className="pt-20">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
